### ISSUE TITLE
how can i use this to enable remote access on a router ?

### ISSUE THREAD

**Issue by minanagehsalalma** [mpgn/ByP-SOP#1]
https://github.com/h43z/dns-rebinding-tool/issues/1

**Comment by minanagehsalalma** [comment]
@mpgn  at least tell me any thing

**Comment by mpgn** [comment]
Not sure what your asking... Create an issue with just a link is not a valid issue for me.

**Comment by minanagehsalalma** [comment]
@mpgn  ok that's  fine 
Let's say that the pass and username are admin.admin
How will the DNS rebinding connect to the router page and enable the remote access .. Send us the WiFi password ..etc
the router model is ZXHN H108N V2.5
"By making a request to the router that enables the remote access"
can't we just get the wifi password back in some sort of response messages ?
...
any way here is the remote access html page ...... the router login page
https://user-images.githubusercontent.com/20546638/55557244-be34a280-56e9-11e9-8136-2e8cc5c912aa.png
https://github.com/h43z/dns-rebinding-tool/files/3043499/ZXHN.H108N.V2.5.zip

**Comment by minanagehsalalma** [comment]
@mpgn  are these  info for you ?
